project:
  title: "quarto-head-foot-disclaim"
  type: website
  output-dir: public

format:
  revealjs:
    height: 900
    width: 1600
    slide-number: true
    scrollable: false
    transition-speed: fast
    footer: "{{< meta date >}} Working papers"
    template-partials:
      - title-slide.html

    title-slide-attributes: 
          data-background-size: auto auto
          data-background-opacity: "0.1"

